Numpy Arraty Vectorization


In [3]:
# convention for importing numpy
import numpy as np
arr = [1,2,3,4,5]
print(type(arr))

<class 'list'>


In [4]:
a = np.array(arr)
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(5,)


In [5]:
# get the dimension of a with ndim
print (a.ndim)

1


In [6]:
b = np.array([[1,2,3],[4,5,6]])
print (b)
print("The Number of dimension of the array:",b.ndim) # 2 dimensional array
print (b.shape) # from the result the shape is 2 rows and 3 columns

[[1 2 3]
 [4 5 6]]
The Number of dimension of the array: 2
(2, 3)


There are also some inbuilt functions that can be used to initialize numpy which include empty(), zeros(), ones(), full(), random.random().

In [7]:
# a 2x3 array with random values
np.random.random((2,3))

array([[0.44256692, 0.90339444, 0.37799159],
       [0.60354916, 0.51800187, 0.89573811]])

In [8]:
# a 2x3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# a 2x3 arrays of ones
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Intra-operability of Arrays and Scalars.



In [11]:
c = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])
print("c+d=", c+d)

print("c*d=",c*d)

print("5/d=",5/d)

print(c**2)





c+d= [[13. 13. 13.]
 [10. 10. 10.]]
c*d= [[36. 40. 42.]
 [ 9. 16. 21.]]
5/d= [[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]
[[81. 64. 49.]
 [ 1.  4.  9.]]


Indexing With Arrays & Using Arrays for Data Processing

In [12]:
a[0] 


1

In [13]:
a[3]

4

In [14]:
b[0,0]

1

In [15]:
b[1,2]

6

In [16]:
c[0,1]

8.0

Advance method of indexing 

In [17]:
# Element in array can be retrreved by using slicing
d[1, 0:2]

array([9., 8.])

In [19]:
e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
# slicing
e[:3,:2]

array([[10, 11],
       [13, 14],
       [16, 17]])